apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: webserver-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/philip860/webserver-operator-bundle:1.0.34-dev
  displayName: WebServer Operator Catalog
  publisher: Philip Duncan (Duncan-Networks)
