apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: webserver-operator
  namespace: webserver-operator-system
spec:
  channel: stable
  name: webserver-operator
  source: webserver-operator-catalog
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
