apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webserver-operator
  namespace: webserver-operator-system
subjects:
  - kind: ServiceAccount
    name: webserver-operator
    namespace: webserver-operator-system
roleRef:
  kind: Role
  name: webserver-operator
  apiGroup: rbac.authorization.k8s.io
