apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webserver-operator
  namespace: webserver-operator-system
rules:
  # Watch & manage CRs
  - apiGroups: ["example.com"]
    resources: ["webservers", "webservers/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Manage workloads
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
